apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devopsflow.fullname" . }}
  labels:
    {{- include "devopsflow.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
